=== deno207/Inventory-Caretaker/src/test/resources/database-data-sets/database.dtd
<!ELEMENT dataset (
    Address*,
    Category*,
    StockItem*,
    StockItem_SubItem*,
    StockItem_Supplier*,
    SubItem*,
    Supplier*)>

<!ELEMENT Address EMPTY>
<!ATTLIST Address
    id CDATA #REQUIRED
    city CDATA #IMPLIED
    country CDATA #IMPLIED
    county CDATA #IMPLIED
    lineOne CDATA #IMPLIED
    lineTwo CDATA #IMPLIED
    postCode CDATA #IMPLIED
>

<!ELEMENT Category EMPTY>
<!ATTLIST Category
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    imageName CDATA #IMPLIED
    name CDATA #IMPLIED
    parent_id CDATA #IMPLIED
>

<!ELEMENT StockItem EMPTY>
<!ATTLIST StockItem
    id CDATA #REQUIRED
    currentStock CDATA #REQUIRED
    description CDATA #IMPLIED
    hasSubItem CDATA #REQUIRED
    imageName CDATA #IMPLIED
    lowStock CDATA #REQUIRED
    measurementType CDATA #IMPLIED
    name CDATA #IMPLIED
    subItemPlural CDATA #IMPLIED
    subItemSingular CDATA #IMPLIED
    category_id CDATA #IMPLIED
>

<!ELEMENT StockItem_SubItem EMPTY>
<!ATTLIST StockItem_SubItem
    StockItem_id CDATA #REQUIRED
    subItems_id CDATA #REQUIRED
>

<!ELEMENT StockItem_Supplier EMPTY>
<!ATTLIST StockItem_Supplier
    StockItem_id CDATA #REQUIRED
    suppliers_id CDATA #REQUIRED
>

<!ELEMENT SubItem EMPTY>
<!ATTLIST SubItem
    id CDATA #REQUIRED
    amount CDATA #REQUIRED
    displayId CDATA #IMPLIED
    location CDATA #IMPLIED
>

<!ELEMENT Supplier EMPTY>
<!ATTLIST Supplier
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    imageName CDATA #IMPLIED
    name CDATA #IMPLIED
    phoneNumber CDATA #IMPLIED
    website CDATA #IMPLIED
    address_id CDATA #IMPLIED
>

=== deno207/Inventory-Caretaker/src/test/resources/database-data-sets/base-sets/base-dataset-plus-stock-item-with-subitem.xml
<!DOCTYPE dataset SYSTEM "../database.dtd">
<dataset>
    <Address id="1" city="Crugybar" country="UK" county="Llanwrda" lineOne="The Old Post Office" postCode="SA19 8TH"/>
    <Category id="1" description="All of the fruit" imageName="" name="Fruit"/>
    <StockItem id="1" currentStock="0.0" description="A yellow fruit with a sour taste" hasSubItem="1" imageName="" lowStock="10.0" measurementType="3" name="Lemon" subItemPlural="Pallets" subItemSingular="Pallet" category_id="1"/>
    <StockItem id="2" currentStock="0.0" description="A red or green round fruit that is grown on trees" hasSubItem="1" imageName="" lowStock="10.0" measurementType="3" name="Apple" subItemSingular="Pallet" subItemPlural="Pallets"/>
    <StockItem_SubItem StockItem_id="1" subItems_id="1"/>
    <StockItem_Supplier StockItem_id="1" suppliers_id="1"/>
    <SubItem id="1" amount="0.0" location="In Cardboard" displayId="Pallet 1"/>
    <Supplier id="1" description="The Supplier of all fruity needs" imageName="" name="Fruit Inc" address_id="1"/>
</dataset>
